name: Publish

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

permissions: {}

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: Run actionlint

    runs-on: ubuntu-latest

    timeout-minutes: 5

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@e3d2460bbb42d7710191569f88069044cfb9d8cf # v4.2.2

      - name: Run actionlint
        run: |
          set -x
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint

  secretlint:
    name: Run secretlint

    runs-on: ubuntu-latest

    timeout-minutes: 5

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@e3d2460bbb42d7710191569f88069044cfb9d8cf # v4.2.2

      - name: Run secretlint
        run: |
          set -x
          docker run -v `pwd`:`pwd` -w `pwd` --rm -it secretlint/secretlint secretlint "**/*"

  release:
    name: Run release-please

    needs: [actionlint, secretlint]

    runs-on: ubuntu-latest

    timeout-minutes: 5

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Run release-please
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        id: release
        with:
          release-type: node
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      - name: Checkout
        uses: actions/checkout@e3d2460bbb42d7710191569f88069044cfb9d8cf # v4.2.2
        if: ${{ steps.release.outputs.release_created }}

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 22
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Publish npm
        run: |
          set -x
          pnpm install
          pnpm publish --no-git-checks
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
